name: HACS Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          # When RPI_GPIO brand icons merged https://github.com/home-assistant/brands/pull/3132 this integration (RPI_RF)
          # will need a pull request for a Symbolic Link to that one (RPI_GPIO)
          ignore: "brands"