name: HACS Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Brand icons pull request made, will probably not be merged until core integration is depreciated in 2022.4  https://github.com/home-assistant/brands/pull/3175 
          ignore: "brands"
